firework_desktop_particules:
  type: integer
  default: 50
  description:
    en: How many particules to display. 0 to disable.
firework_desktop_particule_size:
  type: integer
  default: 5
  description:
    en: Particle size in pixels.
firework_desktop_width:
  type: integer
  default: 500
  description:
    en: Width in pixels of a firework.
firework_desktop_height:
  type: integer
  default: 500
  description:
    en: Height in pixels of a firework.
firework_desktop_gravity:
  type: integer
  default: 200
  description:
    en: Particle fall distance in pixels.

firework_mobile_particules:
  type: integer
  label: Particules
  default: 50
  description:
    en: How many particules to display. 0 to disable.
firework_mobile_particule_size:
  type: integer
  default: 3
  description:
    en: Particle size in pixels.
firework_mobile_width:
  type: integer
  default: 200
  description:
    en: Width in pixels of the explosion
firework_mobile_height:
  type: integer
  default: 200
  description:
    en: Height in pixels of the explosion
firework_mobile_gravity:
  type: integer
  default: 200
  description:
    en: Particle fall distance in pixels.
use_tsParticles_fireworks:
  type: bool
  default: false
  description:
    en: Use tsParticles' fireworks instead of CSS' This creates more realistic fireworks, in addition to sound. This is only available on desktop.
tsParticles_fireworks_sound_enabled:
  type: bool
  default: false
  description:
    en: Enable or disable sound from tsParticle's fireworks. Defaults to off.
tsParticles_fireworks_rate:
  type: integer
  default: 10
  min: 1
  max: 50
  description:
    # Placed in "" so that the ':' after 'WARNING' can be used
    en: "Rate of tsParticle's fireworks. Defaults to 10. WARNING: Putting a value higher than 10 will fill your screen with fireworks."
